# Generated by Django 4.2.7 on 2023-11-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.TextField(blank=True, max_length=12)),
                ('personal_email', models.EmailField(max_length=30)),
                ('grade', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.TextField(blank=True, max_length=12)),
                ('personal_email', models.EmailField(max_length=30)),
                ('discipline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic', models.TextField()),
                ('material_link', models.URLField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_DRF.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_DRF.teacher')),
            ],
        ),
    ]
