# Generated by Django 4.2.7 on 2023-11-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_DRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
