# Generated by Django 4.2.7 on 2023-12-25 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_DRF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, max_length=950, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='telegram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='vk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('task', models.TextField()),
                ('description', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_DRF.project')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_DRF.tasks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_DRF.tasks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
