# Generated by Django 4.2.7 on 2023-12-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_DRF', '0002_remove_student_phone_number_account_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='project_id',
            new_name='project',
        ),
    ]
