# Generated by Django 4.2.7 on 2023-11-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_DRF', '0002_rename_student_id_project_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('login', models.TextField(unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
