# Generated by Django 4.2.7 on 2023-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_DRF', '0003_rename_project_id_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='material_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
