# Generated by Django 4.2.7 on 2023-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_DRF', '0003_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='first_name_proponent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='last_name_proponent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='patronymic_proponent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='first_name_proponent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_name_proponent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='patronymic_proponent',
            field=models.TextField(null=True),
        ),
    ]
