# Generated by Django 4.2.7 on 2023-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_DRF', '0004_project_completion_project_user_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='discipline',
            field=models.TextField(blank=True),
        ),
    ]
